### PR TITLE
Refactored some code and pulled out components into separate files

### PR DESCRIPTION
**Pull request by RichardPilbery**
As the maps grows, I thought it might be helpful to separate the components.

### CODE REVIEW

**Comment by nistei** [comment]
In `package.json` tsc only compiles the map file currently.

**Comment by nistei** [comment]
The map is not showing all planes.

It does only make the first request. Follow up requests for the pagination are not sent.

**Comment by nistei** [comment]
Search Bar suggestions aren't working

**Comment by RichardPilbery** [comment]
Hi @nistei, is this with the changes I've just made? I've pulled 400+ planes in and the search function is working...

**Comment by RichardPilbery** [comment]
Apologies, you're right about only pulling in the first 100 planes.

**Comment by nistei** [comment]
Only the first 100.
The search function is working, I can select a plane when entering the full flight number. When typing it was showing a list with all results matching the current search term. I do not get this autocomplete functionality now.

**Comment by RichardPilbery** [comment]
Ah, okay.

**Comment by nistei** [comment]
Airport icons also do not show until the flights get reloaded.

**Pull request closed without merging**
